name: Deploy on github actions runner

on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted
    environment: loki

    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v4

      - name: Deploy to my server
        run: |
          cd $PROJECT_HOME
          git pull origin main
          echo "Deploy to $(pwd)"
          source venv/bin/activate
          pip install -r requirements.txt
          sudo /bin/systemctl restart fvh-api.service
          sudo /bin/systemctl restart fvh-gui.service
        env:
          PROJECT_HOME: ${{ vars.PROJECT_HOME }}
