name: Main Workflow

on: [push]

permissions:
  contents: read

jobs:
  run_codeql:
    uses: ./.github/workflows/codeql.yml
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: read

  run_pylint:
    uses: ./.github/workflows/pylint.yml
    permissions:
      contents: read

  run_bandit:
    uses: ./.github/workflows/bandit.yml
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

  deploy_application:
    needs: [run_codeql, run_pylint, run_bandit]
    uses: ./.github/workflows/deploy-and-restart-api.yml
