name: Main Workflow

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run_codeql:
    uses: ./.github/workflows/codeql.yml
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: read

  run_pylint:
    uses: ./.github/workflows/pylint.yml
    permissions:
      contents: read

  deploy_application:
    needs: [run_codeql, run_pylint, run_bandit]
    uses: ./.github/workflows/deploy-and-restart-api.yml
